pixelwalker/engine/urls.py
from django.urls import path

from .webgui import views_assessment as assessment
from .webgui import views_media as media
from .webgui import views_encoding_provider as encoding_provider
from .webgui import views_task as task
from .webgui import views_app_settings as app_settings
from .webgui import views_chart_annotation as chart_annotation

urlpatterns = [
    # WEBGUI
    # Assessment
    path('', assessment.list, name='webgui_assessment-list'),   
    path('assessment', assessment.list, name='webgui_assessment-list'),   
    path('assessment/create', assessment.create, name='webgui_assessment-create'),   
    path('assessment/<int:assessment_id>', assessment.read, name='webgui_assessment-read'),   
    path('assessment/<int:assessment_id>/update', assessment.update, name='webgui_assessment-update'),   
    path('assessment/<int:assessment_id>/delete', assessment.delete, name='webgui_assessment-delete'),
    path('assessment/<int:assessment_id>/chart', assessment.chart, name='webgui_assessment-chart'),
    # Media
    path('media', media.list, name='webgui_media-list'),  
    path('media/create', media.create, name='webgui_media-create'),  
    path('media/<int:media_id>', media.read, name='webgui_media-read'),  
    path('media/<int:media_id>/update', media.update, name='webgui_media-update'),  
    path('media/<int:media_id>/delete', media.delete, name='webgui_media-delete'),  
    path('media/<int:media_id>/chart/frames', media.chart_frames, name='webgui_media-chart-frames'),  
    path('media/<int:media_id>/probe', media.display_probe, name='webgui_media-display-probe'),  
    # EncodingProvider
    path('encoding_provider', encoding_provider.list, name='webgui_encoding-provider-list'),   
    path('encoding_provider/create', encoding_provider.create, name='webgui_encoding-provider-create'),   
    path('encoding_provider/<int:encoding_provider_id>', encoding_provider.read, name='webgui_encoding-provider-read'),   
    path('encoding_provider/<int:encoding_provider_id>/update', encoding_provider.update, name='webgui_encoding-provider-update'),   
    path('encoding_provider/<int:encoding_provider_id>/delete', encoding_provider.delete, name='webgui_encoding-provider-delete'),   
    # Task
    path('task', task.list, name='webgui_task-list'),
    path('task/create', task.create, name='webgui_task-create'),  
    path('task/<int:task_id>', task.read, name='webgui_task-read'), 
    path('task/<int:task_id>/redo', task.redo, name='webgui_task-redo'), 
    path('task/<int:task_id>/abort', task.abort, name='webgui_task-abort'), 
    # AppSettings
    path('app_settings', app_settings.read, name='webgui_app-settings-read'),   
    path('app_settings/update', app_settings.update, name='webgui_app-settings-update'),
    # Chart Annotations
    path('chart_annotation/create', chart_annotation.create, name='webgui_chart-annotation-create'),  
    path('chart_annotation/<int:annotation_id>/delete', chart_annotation.delete, name='webgui_chart-annotation-delete'), 
]

pixelwalker/engine/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.conf import settings
from django.utils import timezone
import os, json, json2table
from natsort import natsorted, ns
from celery.execute import send_task

from . import utils


class AppSetting(models.Model):
    key = models.CharField(max_length=32, null=False, default='unnamed parameter')
    value = models.CharField(max_length=32, null=True)
    is_bool = models.BooleanField(default=False)
    description = models.CharField(max_length=280, null=True)
    

class EncodingProvider(models.Model):
    name = models.CharField(max_length=200, null=False, default='unnamed encoding provider')

    def get_number_of_media(self):
        media_list = Media.objects.filter(encoding_provider=self)
        return len(media_list)

    def get_some_media_preview(self):
        media_list = Media.objects.filter(encoding_provider=self).order_by('-id')[:5]
        return media_list


class Media(models.Model):
    name = models.CharField(max_length=200, null=False, default='unnamed media')
    file = models.FileField(null=True, upload_to=utils.get_upload_path)
    encoding_provider = models.ForeignKey(EncodingProvider, null=True, on_delete=models.SET_NULL)
    width = models.IntegerField(null=True)
    height = models.IntegerField(null=True)
    average_bitrate = models.CharField(max_length=50, null=True)
    video_codec = models.CharField(max_length=50, null=True)
    framerate = models.IntegerField(null=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)

    def extension(self):
        name, extension = os.path.splitext(self.file.name)
        return extension

    def auto_submit_task(self, type_name):
        new_task = Task()
        new_task.assessment = None
        new_task.media = Media.objects.get(id=self.id)
        new_task.type = TaskType.objects.get(name=type_name)
        new_task.save()
        new_task.submit()

    def get_file_url(self):
        return settings.MEDIA_URL+self.file.path.replace(settings.MEDIA_ROOT+'\\','').replace(settings.MEDIA_ROOT+'/','').replace('\\','/')

    def get_thumbnail_url(self):
        task = Task.objects.filter(media=self, type=TaskType.objects.get(name='GENERATE THUMBNAILS'), state=Task.SUCCESS).last()
        output = TaskOutput.objects.filter(task=task, type=TaskOutput.MEDIA).last()
        if output is not None:
            return output.get_url().replace("%05d","00001")
        else:
            return None
    
    def get_probe_html_table(self):
        task = Task.objects.filter(media=self, type=TaskType.objects.get(name='PROBE'), state=Task.SUCCESS).last()
        output = TaskOutput.objects.filter(task=task, type=TaskOutput.JSON).last()
        if output is not None:
            return json2table.convert(json.load(open(output.file_path)), build_direction="LEFT_TO_RIGHT", table_attributes={"class" : "table table-bordered table-hover table-condensed"})
        else:
            return None
    
    def get_frames_labels(self):
        task = Task.objects.filter(media=self, type=TaskType.objects.get(name='FRAMES ANALYSIS'), state=Task.SUCCESS).last()
        if task:
            return task.get_output_labels()
        else:
            return None

    def get_frames_PTS(self):
        task = Task.objects.filter(media=self, type=TaskType.objects.get(name='FRAMES ANALYSIS'), state=Task.SUCCESS).last()
        if task:
            return task.get_output_data_by_name('PTS Time')
        else:
            return '[]'
    
    def get_frames_I(self):
        task = Task.objects.filter(media=self, type=TaskType.objects.get(name='FRAMES ANALYSIS'), state=Task.SUCCESS).last()
        if task:
            return task.get_output_data_by_name('I Frames')
        else:
            return '[]'

    def get_frames_I_count(self):
        task = Task.objects.filter(media=self, type=TaskType.objects.get(name='FRAMES ANALYSIS'), state=Task.SUCCESS).last()
        if task:
            return int(task.get_output_average_by_name('I Frames'))
        else:
            return 0
    
    def get_frames_P(self):
        task = Task.objects.filter(media=self, type=TaskType.objects.get(name='FRAMES ANALYSIS'), state=Task.SUCCESS).last()
        if task:
            return task.get_output_data_by_name('P Frames')
        else:
            return '[]'

    def get_frames_P_count(self):
        task = Task.objects.filter(media=self, type=TaskType.objects.get(name='FRAMES ANALYSIS'), state=Task.SUCCESS).last()
        if task:
            return int(task.get_output_average_by_name('P Frames'))
        else:
            return 0

    def get_frames_B(self):
        task = Task.objects.filter(media=self, type=TaskType.objects.get(name='FRAMES ANALYSIS'), state=Task.SUCCESS).last()
        if task:
            return task.get_output_data_by_name('B Frames')
        else:
            return '[]'
    
    def get_frames_B_count(self):
        task = Task.objects.filter(media=self, type=TaskType.objects.get(name='FRAMES ANALYSIS'), state=Task.SUCCESS).last()
        if task:
            return int(task.get_output_average_by_name('B Frames'))
        else:
            return 0

    def get_definition(self):
        return str(self.width)+'x'+str(self.height)

    

class Assessment(models.Model):
    name = models.CharField(max_length=200, null=False, default='unnamed assessment')
    description = models.CharField(max_length=500, null=True)
    encoded_media_list = models.ManyToManyField(Media, related_name='encoded_media_list')
    reference_media = models.ForeignKey(Media, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)

    def get_definition_list(self):
        definition_list = []
        for media in self.encoded_media_list.all():
            if media.get_definition() not in definition_list:
                definition_list.append(media.get_definition())
        return natsorted(definition_list)

    def get_encoding_provider_list(self):
        encoding_provider_list = []
        for media in self.encoded_media_list.all():
            if media.encoding_provider not in encoding_provider_list:
                encoding_provider_list.append(media.encoding_provider)
        return encoding_provider_list

    def get_bitrate_list(self):
        bitrate_list = []
        for media in self.encoded_media_list.all().order_by('average_bitrate'):
            if media.average_bitrate not in bitrate_list:
                bitrate_list.append(media.average_bitrate)
        return bitrate_list
    
    def get_min_bitrate(self):
        return min(self.get_bitrate_list())
    
    def get_max_bitrate(self):
        return max(self.get_bitrate_list())

    def get_all_frames_labels(self):
        task = Task.objects.filter(assessment=self, state=Task.SUCCESS).last()
        if task:
            return task.get_output_labels()
        else:
            return '[]'
        




class TaskType(models.Model):
    name = models.CharField(max_length=200, null=False, default='unnamed task type')
    is_video_metric = models.BooleanField(default=False)
    auto_submit_on_new_media = models.BooleanField(default=False)


class Task(models.Model):
    media = models.ForeignKey(Media, null=False, on_delete=models.CASCADE)
    assessment = models.ForeignKey(Assessment, null=True, on_delete=models.CASCADE)
    type = models.ForeignKey(TaskType, null=False, on_delete=models.CASCADE)

    QUEUED = 0
    PROCESSING = 1
    SUCCESS = 2
    ERROR = 3
    ABORTED = 4
    STATE_CHOICES = (
        (QUEUED, 'Queued'),
        (PROCESSING, 'Processing'),
        (SUCCESS, 'Success'),
        (ERROR, 'Error'),
        (ABORTED, 'Aborted'),
    )
    state = models.IntegerField(default=QUEUED, choices=STATE_CHOICES)
    progress = models.IntegerField(null=True)
        
    date_created = models.DateTimeField('date created', null=False, auto_now_add=True)
    date_queued = models.DateTimeField('date queued', null=True)
    date_started = models.DateTimeField('date started', null=True)
    date_ended = models.DateTimeField('date ended', null=True)

    def submit(self):
        self.date_queued = timezone.now()
        self.state = Task.QUEUED
        self.save()

        # Prepare to send task to available worker
        data = {}
        data['id'] = self.id
        data['media_file_path'] = self.media.file.path
        if self.media.framerate:
            data['media_framerate'] = self.media.framerate
        if self.assessment:
            data['reference_file_path'] = self.assessment.reference_media.file.path
            data['reference_width'] = self.assessment.reference_media.width
            data['reference_height'] = self.assessment.reference_media.height
        data['type'] = self.type.name
        send_task('worker.tasks.add', args=[data])
    
    def get_average_score(self):
        output = TaskOutput.objects.filter(task=self, type=TaskOutput.CHART_DATA).last()
        return output.average
    
    def get_output_labels(self):
        output = TaskOutput.objects.filter(task=self, type=TaskOutput.CHART_LABELS).last()
        if output:
            labels = json.load(open(output.file_path))
            return json.dumps(labels)
        else:
            return '[]'

    def get_output_data(self):
        output = TaskOutput.objects.filter(task=self, type=TaskOutput.CHART_DATA).last()
        if output:
            data = json.load(open(output.file_path))
            return json.dumps(data)
        else:
            return '[]'

    def get_output_data_by_name(self, ouput_name):
        output = TaskOutput.objects.filter(task=self, type=TaskOutput.CHART_DATA, name=ouput_name).last()
        if output:
            data = json.load(open(output.file_path))
            return json.dumps(data)
        else:
            return '[]'
    
    def get_output_average_by_name(self, ouput_name):

pixelwalker/engine/webgui/templates/task/list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block tab_title %}{{ block.super }}: Tasks{% endblock %}

{% block nav %}
    <ul>
        <li><a href="{% url 'webgui_assessment-list' %}">Assessments</a></li>
        <li><a href="{% url 'webgui_media-list' %}">Media</a></li>
        <li><a href="{% url 'webgui_encoding-provider-list' %}">Encoding providers</a></li>
        <li><a href="{% url 'webgui_task-list' %}" class='active'>Tasks</a></li>
    </ul>
{% endblock %}

{% block options %}
    <ul>
        {% is_task_list_auto_refresh_enabled as refresh_enabled %}
        {% if refresh_enabled %} 
        <li>
            <label class="checkbox-inline">
                <input type="checkbox" id="autorefresh" name='autorefresh' checked data-toggle="toggle" data-size="mini" data-on="<i class='fa fa-refresh'></i>" data-off="<i class='fa fa-ban'></i>">
                Auto-refresh
            </label>
        </li>
        {% endif %}
    </ul>
{% endblock %}

{% block content %}       
    {% if task_list %}
    <div id="tasks">

            <!-- class="search" automagically makes an input a search field. -->
            <div class="form-group col-xs-12 col-md-6">
                <input class="search form-control" placeholder="Search" />
            </div>
        
            <!-- class="sort" automagically makes an element a sort buttons. The date-sort value decides what to sort by. -->
            <div class="form-group col-xs-12 col-md-6">
                <button class="sort btn btn-default" data-sort="id"><i class='fa fa-sort'></i> Id</button>
                <button class="sort btn btn-default" data-sort="type"><i class='fa fa-sort'></i> Type</button>
                <button class="sort btn btn-default" data-sort="state"><i class='fa fa-sort'></i> State</button>
                <button class="sort btn btn-default" data-sort="media"><i class='fa fa-sort'></i> Media</button>
                <button class="sort btn btn-default" data-sort="assessment"><i class='fa fa-sort'></i> Assessment</button>
            </div>          
        
            <ul class="list col-xs-12">
            {% for task in task_list %}
                <li class='item'>
                        <div class='general'>
                            <a href="{% url 'webgui_task-read' task.id %}" class="name id"><b>#{{ task.id }}</b></span></a>
                            <p class='desc'>
                                <span class="type">{{ task.type.name }}</span><br>
                                <a href="{% url 'webgui_media-read' task.media.id %}" class="media">{{ task.media.name }}</a>
                            </p>
                        </div>
        
                        <ul class='infos'>
                            {% if task.state == 1 %}
                            <li><span class="state label label-primary">{{ task.get_state_display }}</span></li>
                            {% elif task.state == 2 %}
                            <li><span class="state label label-success">{{ task.get_state_display }}</span></li>
                            {% elif task.state == 3 %}
                            <li><span class="state label label-danger">{{ task.get_state_display }}</span></li>
                            {% elif task.state == 4 %}
                            <li><span class="state label label-warning">{{ task.get_state_display }}</span></li>
                            {% else %}
                            <li><span class="state label label-default">{{ task.get_state_display }}</span></li>
                            {% endif %}
                            {% if task.assessment %}
                            <li><br></li>
                            <li>Assessment: <a href="{% url 'webgui_assessment-read'  task.assessment.id %}" class="assessment">{{ task.assessment.name }}</a></li>
                            {% endif %}
                        </ul>

                        <ul class='actions'>
                            <li><a href="{% url 'webgui_task-read' task.id %}"><i class='fa fa-eye'></i> View</a></li>
                            {% if task.state > 1 %}
                            <li><a href="{% url 'webgui_task-redo' task.id %}"><i class='fa fa-refresh'></i> Redo</a></li>
                            {% endif %}
                            {% if task.state < 2 %}
                            <li><a href="{% url 'webgui_task-abort' task.id %}"><i class='fa fa-times'></i> Abort</a></li>
                            {% endif %}
                        </ul>
                </li>
            {% endfor %}
            </ul>
            <ul class="pagination"></ul>
        </div>
    {% else %}
        <p class='col-sm-7 danger'>No task to display.</p>
    {% endif %}

{% endblock %}

{% block css_requirements %}
    {{ block.super }}
    <link href="{% static 'bower_components/bootstrap-toggle/css/bootstrap-toggle.min.css' %}" rel="stylesheet">
{% endblock %}

{% block js_requirements %}
    {{ block.super }}
    <script src="{% static 'bower_components/list.js/dist/list.min.js' %}"></script>
    <script src="{% static 'bower_components/bootstrap-toggle/js/bootstrap-toggle.min.js' %}"></script>
{% endblock %}

{% block javascript %}
    {{ block.super }}
    <script>
        $(document).ready(function(){
            {% is_task_list_auto_refresh_enabled as refresh_enabled %}
            {% if refresh_enabled %} 
            setInterval(function(){
                console.log($("#autorefresh").prop('checked'))
                if($("#autorefresh").prop('checked'))
                {
                    window.location.reload(1);
                }
            }, 5000);
            {% endif %}
        }); 

        var options = {
            valueNames: [ 'id', 'type', 'state', 'media', 'assessment' ],
            page: 10,
            pagination: true
        };
        var taskList = new List('tasks', options);
    </script>
{% endblock %}

pixelwalker/engine/webgui/templates/task/read.html
{% extends "base.html" %}
{% load staticfiles %}

{% block tab_title %}{{ block.super }}: Tasks{% endblock %}

{% block nav %}
    <ul>
        <li><a href="{% url 'webgui_assessment-list' %}">Assessments</a></li>
        <li><a href="{% url 'webgui_media-list' %}">Media</a></li>
        <li><a href="{% url 'webgui_encoding-provider-list' %}">Encoding providers</a></li>
        <li><a href="{% url 'webgui_task-list' %}" class='active'>Tasks</a></li>
    </ul>
{% endblock %}

{% block options %}
    <ul>
        <li><a href='#' onclick='goBack()'><i class='fa fa-caret-left'></i> Back</a></li>
        {% if task.state > 1 %}
        <li><a href="{% url 'webgui_task-redo' task.id %}"><i class='fa fa-refresh'></i> Redo</a></li>
        {% endif %}
        {% if task.state < 2 %}
        <li><a href="{% url 'webgui_task-abort' task.id %}"><i class='fa fa-times'></i> Abort</a></li>
        {% endif %}
    </ul>
{% endblock %}

{% block content %}       
<h4>
    <span class='info'>Task:</span> #{{ task.id }}<br>
    {% if task.state == 1 %}
    <span class="state label label-default label-primary">{{ task.get_state_display }}</span>
    {% elif task.state == 2 %}
    <span class="state label label-default label-success">{{ task.get_state_display }}</span>
    {% elif task.state == 3 %}
    <span class="state label label-default label-danger">{{ task.get_state_display }}</span>
    {% elif task.state == 4 %}
    <span class="state label label-default label-warning">{{ task.get_state_display }}</span>
    {% else %}
    <span class="state label label-default">{{ task.get_state_display }}</span>
    {% endif %}
</h4>

<table class='table table-striped table-condensed'>
    <thead>
        <tr>
            <th colspan='3'><i class='fa fa-exchange'></i> Relationships</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><b>Type</b></td>
            <td><b>Assessment</b></td>
            <td><b>Media</b></td>
        </tr>
        <tr>
            <td>{{ task.type.name }}</td>
            <td>
                {% if task.assessment %}
                <a href="{% url 'webgui_assessment-read'  task.assessment.id %}">{{ task.assessment.name }}</a>
                {% else %}
                <i>None</i>
                {% endif %}
            </td>
            <td><a href="{% url 'webgui_media-read'  task.media.id %}">{{ task.media.name }}</a></td>
        </tr>
    </tbody>
</table>

<table class='table table-striped table-condensed'>
    <thead>
        <tr>
            <th colspan='3'><i class='fa fa-calendar'></i> Time informations</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><b>Created</b></td>
            <td><b>Last queued</b></td>
            <td><b>Process started</b></td>
            <td><b>Process ended</b></td>
        </tr>
        <tr>
            <td>{{ task.date_created }}</td>
            <td>{{ task.date_queued }}</td>
            <td>{{ task.date_started }}</td>
            <td>{{ task.date_ended }}</td>
        </tr>
    </tbody>
</table>

<table class='table table-striped table-condensed'>
    <thead>
        <tr>
            <th colspan='3'><i class='fa fa-inbox'></i> Outputs</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><b>Name</b></td>
            <td><b>Type</b></td>
            <td><b>Output</b></td>
        </tr>
        {% for output in output_list %}
        <tr>
            <td>{{ output.name }}</td>
            <td>{{ output.get_type_display }}</td>
            <td><a href="{{ output.get_url }}" target='output_{{ output.id }}'>{{ output.file_path }}</a></td>
        </tr>
        {% if output.average %}
        <tr>
            <td>{{ output.name }}</td>
            <td>Average</td>
            <td>{{ output.average }}</td>
        </tr>
        {% endif %}
        {% empty %}
        <tr>
            <td colspan='3'><i>No existing output to be displayed</i></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

{% block css_requirements %}
    {{ block.super }}
{% endblock %}

{% block js_requirements %}
    {{ block.super }}
{% endblock %}